import { StyleSheet } from 'react-native';

export const roundButton = {
    width: '5%',
    height: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 100,
    borderSyyle: 'solid',
    borderWidth: 1,
};

export const styles = StyleSheet.create({
  mainView: {
    flexGrow: 1,
    marginTop: 43,
//    justifyContent: 'flex-start',
    backgroundColor: '#000000',
    color: '#ffffff',
    height: '90%',
    flexDirection: 'column',
  },
  svcontainer: {
    flexGrow: 0,
//    backgroundColor: '#f0f0f0',
    backgroundColor: '#000000',
//    alignItems: 'center',
//    justifyContent: 'center',
//    marginTop: 50,
    marginLeft: 0,
    marginBottom: 100,
    color: '#ffffff',
  },
  top: {
    flexGrow: 0,
    justifyContent: 'flex-start',
    width: '97%',
    marginLeft: 5,
//    alignItems: 'center',
    marginTop: 0,
//    marginLeft: 0,
//    width: '100%',
    backgroundColor: '#000000',
  },
  subtasks: {
//    flex: 1,
    flexGrow: 1,
//    flexDirection: 'column',
    gap: 0,
//    alignItems: 'center',
//    padding: 50,
    width: '100%',
  },
  container: {
//    paddingTop: StatusBar.currentHeight,
//    flex: 1,
//    backgroundColor: '#000000',
//    alignItems: 'center',
//    justifyContent: 'center',
//    alignItems: 'center',
//    color: '#000000',
    flexGrow: 1,
    width: '100%',
    borderWidth: 1,
    paddingRight: 0,
    paddingVertical: 0,
    marginBottom: 5,
  },
  item: {
    flexGrow: 1,
    width: '97%',
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingRight: 5,
    paddingVertical: 10,
    marginLeft: 5,
    marginRight: 0,
    marginBottom: 5,
//    backgroundColor: '#ffffff',
    borderColor: 'gray',
    backgroundColor: '#000000',
  },
  itemCurrent: {
    flexGrow: 0,
    width: '97%',
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingRight: 5,
    paddingVertical: 10,
    marginLeft: 5,
    marginRight: 0,
    marginBottom: 5,
//    backgroundColor: '#ffffff',
    borderColor: 'gray',
    backgroundColor: '#000000',
  },
  input: {
    borderColor: 'gray',
    width: '100%',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    color: '#ffffff',
    fontWeight: 'bold',
    backgroundColor: '#000000',
  },
  taskText: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  taskTextSel: {
    color: '#00eeff',
    fontWeight: 'bold',
  },
  roundButton: {
    ...roundButton,
    //redviolet #ff0080
    backgroundColor: '#ffffff',
  },
  roundButtonSel: {
    ...roundButton,
    //yellow #ffff00
    backgroundColor: '#ffff00',
  },
  roundButtonSel1: {
    ...roundButton,
    //yellow #ffff00
    backgroundColor: '#ffff84',
  },
  bottom1: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 36,
    marginLeft: 0,
    width: '100%',
//    flexDirection:"row",
  },
  bottom: {
    flexGrow: 1,
//    flexDirection: 'row',
    width: '98%',
    marginLeft: 5,
    justifyContent: 'flex-end',
//    alignItems: 'center',
    marginBottom: 20,
  },
  statusBar: {
    backgroundColor: '#000000',
  },
  clock: {
//    display: flex,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
});



